services:
  advent:
    image: advent
    container_name: advent
    tty: true
    build:
      context: .
      dockerfile: ./deb.Dockerfile
    volumes:
      - advent_vol:/workspace/aoc2023
      - vscode:/workspace/aoc2023/.vscode

volumes:
  advent_vol:
  vscode: